//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosPruebaTuya.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VariableName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariableName() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PagosPruebaTuya.Common.Resources.VariableName", typeof(VariableName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONNECTIONSTRINSG_TUYAPAGOSPRUEBATECNICA.
        /// </summary>
        public static string CONNECTIONSTRINSG_TUYAPAGOSPRUEBATECNICA_NAME {
            get {
                return ResourceManager.GetString("CONNECTIONSTRINSG_TUYAPAGOSPRUEBATECNICA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR_GENERAL.
        /// </summary>
        public static string ERROR_GENERAL_NAME {
            get {
                return ResourceManager.GetString("ERROR_GENERAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOCONTENT_MSG.
        /// </summary>
        public static string NOCONTENT_MSG_NAME {
            get {
                return ResourceManager.GetString("NOCONTENT_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOCONTENTPROCESS_MSG.
        /// </summary>
        public static string NOCONTENTPROCESS_MSG_NAME {
            get {
                return ResourceManager.GetString("NOCONTENTPROCESS_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REQUIEREPRODUCT_MSG.
        /// </summary>
        public static string REQUIEREPRODUCT_MSG_NAME {
            get {
                return ResourceManager.GetString("REQUIEREPRODUCT_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUCCESS_MSG.
        /// </summary>
        public static string SUCCESS_MSG_NAME {
            get {
                return ResourceManager.GetString("SUCCESS_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_DESCRIPTION.
        /// </summary>
        public static string SW_DESCRIPTION_NAME {
            get {
                return ResourceManager.GetString("SW_DESCRIPTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_EMAIL.
        /// </summary>
        public static string SW_EMAIL_NAME {
            get {
                return ResourceManager.GetString("SW_EMAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_NAME.
        /// </summary>
        public static string SW_NAME_NAME {
            get {
                return ResourceManager.GetString("SW_NAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_TITLE.
        /// </summary>
        public static string SW_TITLE_NAME {
            get {
                return ResourceManager.GetString("SW_TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_URL_JSON.
        /// </summary>
        public static string SW_URL_JSON_NAME {
            get {
                return ResourceManager.GetString("SW_URL_JSON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW_VERSION.
        /// </summary>
        public static string SW_VERSION_NAME {
            get {
                return ResourceManager.GetString("SW_VERSION_NAME", resourceCulture);
            }
        }
    }
}
